<a href="https://colab.research.google.com/github/Akashj22/CognoRise-Infotech/blob/main/cogno3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/tested.csv')
df

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [ ]:
df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [ ]:
df.tail()

PassengerId  Survived  Pclass                          Name     Sex  \
413         1305         0       3            Spector, Mr. Woolf    male   
414         1306         1       1  Oliva y Ocana, Dona. Fermina  female   
415         1307         0       3  Saether, Mr. Simon Sivertsen    male   
416         1308         0       3           Ware, Mr. Frederick    male   
417         1309         0       3      Peter, Master. Michael J    male   

      Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
413   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  39.0      0      0            PC 17758  108.9000  C105        C  
415  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416   NaN      0      0              359309    8.0500   NaN        S  
417   NaN      1      1                2668   22.3583   NaN        C

In [ ]:
df.shape

(418, 12)

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
df['Embarked'].value_counts()

Embarked
S    270
C    102
Q     46
Name: count, dtype: int64

In [ ]:
dfe=pd.get_dummies(df,columns=['Sex','Embarked'],drop_first=True,dtype=int)
dfe

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name   Age  SibSp  Parch  \
0                                Kelly, Mr. James  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  47.0      1      0   
2                       Myles, Mr. Thomas Francis  62.0      0      0   
3                                Wirz, Mr. Albert  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  22.0      1      1   
..                                            ...   ...    ...    ...   
413                            Spector, Mr. Woolf   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen  38.5      0      0   
416                           Ware, Mr. Frederick   NaN      0      0   
417                      Peter, Master. Michael J   NaN      1      1   

                 Ticket      Fare Cabin  Sex_male  Embarked_Q  Embarked_S  
0                330911    7.8292   NaN         1           1           0  
1                363272    7.0000   NaN         0           0           1  
2                240276    9.6875   NaN         1           1           0  
3                315154    8.6625   NaN         1           0           1  
4               3101298   12.2875   NaN         0           0           1  
..                  ...       ...   ...       ...         ...         ...  
413           A.5. 3236    8.0500   NaN         1           0           1  
414            PC 17758  108.9000  C105         0           0           0  
415  SOTON/O.Q. 3101262    7.2500   NaN         1           0           1  
416              359309    8.0500   NaN         1           0           1  
417                2668   22.3583   NaN         1           0           0  

[418 rows x 13 columns]

In [ ]:
dfe.drop(['PassengerId','Name','Ticket','Fare','Cabin'],axis=1,inplace=True)
dfe

Survived  Pclass   Age  SibSp  Parch  Sex_male  Embarked_Q  Embarked_S
0           0       3  34.5      0      0         1           1           0
1           1       3  47.0      1      0         0           0           1
2           0       2  62.0      0      0         1           1           0
3           0       3  27.0      0      0         1           0           1
4           1       3  22.0      1      1         0           0           1
..        ...     ...   ...    ...    ...       ...         ...         ...
413         0       3   NaN      0      0         1           0           1
414         1       1  39.0      0      0         0           0           0
415         0       3  38.5      0      0         1           0           1
416         0       3   NaN      0      0         1           0           1
417         0       3   NaN      1      1         1           0           0

[418 rows x 8 columns]

In [ ]:
dfe['Age'].fillna(df['Age'].median(),inplace=True)

In [ ]:
dfe.isna().sum()

Survived      0
Pclass        0
Age           0
SibSp         0
Parch         0
Sex_male      0
Embarked_Q    0
Embarked_S    0
dtype: int64

In [ ]:
x=dfe.drop(['Survived'],axis=1).values
x

array([[ 3. , 34.5,  0. , ...,  1. ,  1. ,  0. ],
       [ 3. , 47. ,  1. , ...,  0. ,  0. ,  1. ],
       [ 2. , 62. ,  0. , ...,  1. ,  1. ,  0. ],
       ...,
       [ 3. , 38.5,  0. , ...,  1. ,  0. ,  1. ],
       [ 3. , 27. ,  0. , ...,  1. ,  0. ,  1. ],
       [ 3. , 27. ,  1. , ...,  1. ,  0. ,  0. ]])

In [ ]:
y=dfe['Survived'].values
y

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit_transform(x_train)
x_test=scalar.transform(x_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

knn=KNeighborsClassifier()
nav=GaussianNB()
sv=SVC()

lst=[knn,nav,sv]

for i in lst:
  print('model started :',i)
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  print('confusion metrics is')
  print(confusion_matrix(y_test,y_pred))
  print('accuracy score is',accuracy_score(y_test,y_pred))
  print('classification report',classification_report(y_test,y_pred))
  print('model ended')
  print('-'*100)

model started : KNeighborsClassifier()
confusion metrics is
[[76  9]
 [ 0 41]]
accuracy score is 0.9285714285714286
classification report               precision    recall  f1-score   support

           0       1.00      0.89      0.94        85
           1       0.82      1.00      0.90        41

    accuracy                           0.93       126
   macro avg       0.91      0.95      0.92       126
weighted avg       0.94      0.93      0.93       126

model ended
----------------------------------------------------------------------------------------------------
model started : GaussianNB()
confusion metrics is
[[85  0]
 [ 0 41]]
accuracy score is 1.0
classification report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        85
           1       1.00      1.00      1.00        41

    accuracy                           1.00       126
   macro avg       1.00      1.00      1.00       126
weighted avg       1.00      1.00    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
