<a href="https://colab.research.google.com/github/Akashj22/CognoRise-Infotech/blob/main/cognorise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/creditcard.csv')
df

<ipython-input-1-64d86385662c>:3: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('/content/creditcard.csv')


Time        V1         V2        V3        V4        V5        V6  \
0          0 -1.359807  -0.072781  2.536347  1.378155 -0.338321  0.462388   
1          0  1.191857   0.266151  0.166480  0.448154  0.060018 -0.082361   
2          1 -1.358354  -1.340163  1.773209  0.379780 -0.503198  1.800499   
3          1 -0.966272  -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4          2 -1.158233   0.877737  1.548718  0.403034 -0.407193  0.095921   
...      ...       ...        ...       ...       ...       ...       ...   
33755  37372  0.597155  -1.457940  0.648770 -1.154721 -1.384692 -0.114190   
33756  37373 -7.504323 -15.633772 -4.215051  1.507090 -5.412604  3.243205   
33757  37373  1.242547   0.010297 -1.206012  0.083576  2.171891  3.391877   
33758  37373 -1.065865   1.177477  2.083773  1.296198  0.564073  0.295974   
33759  37373 -0.302250   0.828254 -0.311542 -1.108255  2.533421  3.274040   

             V7        V8        V9  ...       V21                  V22  \
0      0.239599  0.098698  0.363787  ... -0.018307             0.277838   
1     -0.078803  0.085102 -0.255425  ... -0.225775            -0.638672   
2      0.791461  0.247676 -1.514654  ...  0.247998             0.771679   
3      0.237609  0.377436 -1.387024  ... -0.108300             0.005274   
4      0.592941 -0.270533  0.817739  ... -0.009431             0.798278   
...         ...       ...       ...  ...       ...                  ...   
33755 -0.353940  0.077492  1.434997  ...  0.266727    0.391858868587825   
33756  4.422388 -0.423582  0.392031  ...  2.323590    -2.53917289990935   
33757 -0.417041  0.793206 -0.149793  ...  0.031822  -0.0638428726104072   
33758  0.656915  0.158767 -1.006866  ... -0.157601   -0.518893364163089   
33759  0.134693  0.933364 -0.505897  ... -0.314500                    -   

            V23       V24       V25       V26       V27       V28   Amount  \
0     -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   149.62   
1      0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724     2.69   
2      0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   378.66   
3     -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   123.50   
4     -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153    69.99   
...         ...       ...       ...       ...       ...       ...      ...   
33755 -0.248812  0.335329  0.164725 -0.063462  0.010369  0.068737   300.00   
33756 -3.736852 -0.792271 -1.694790 -0.463947 -0.703180  0.780931  4476.72   
33757 -0.166334  1.008827  0.824605 -0.268009  0.016069  0.019513    28.56   
33758 -0.140236 -0.022273  0.117122 -0.358995 -0.201863  0.088919     0.00   
33759       NaN       NaN       NaN       NaN       NaN       NaN      NaN   

       Class  
0        0.0  
1        0.0  
2        0.0  
3        0.0  
4        0.0  
...      ...  
33755    0.0  
33756    0.0  
33757    0.0  
33758    0.0  
33759    NaN  

[33760 rows x 31 columns]

In [2]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0     0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1     0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2     1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3     1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4     2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62    0.0  
1  0.125895 -0.008983  0.014724    2.69    0.0  
2 -0.139097 -0.055353 -0.059752  378.66    0.0  
3 -0.221929  0.062723  0.061458  123.50    0.0  
4  0.502292  0.219422  0.215153   69.99    0.0  

[5 rows x 31 columns]

In [3]:
df.tail()

Time        V1         V2        V3        V4        V5        V6  \
33755  37372  0.597155  -1.457940  0.648770 -1.154721 -1.384692 -0.114190   
33756  37373 -7.504323 -15.633772 -4.215051  1.507090 -5.412604  3.243205   
33757  37373  1.242547   0.010297 -1.206012  0.083576  2.171891  3.391877   
33758  37373 -1.065865   1.177477  2.083773  1.296198  0.564073  0.295974   
33759  37373 -0.302250   0.828254 -0.311542 -1.108255  2.533421  3.274040   

             V7        V8        V9  ...       V21                  V22  \
33755 -0.353940  0.077492  1.434997  ...  0.266727    0.391858868587825   
33756  4.422388 -0.423582  0.392031  ...  2.323590    -2.53917289990935   
33757 -0.417041  0.793206 -0.149793  ...  0.031822  -0.0638428726104072   
33758  0.656915  0.158767 -1.006866  ... -0.157601   -0.518893364163089   
33759  0.134693  0.933364 -0.505897  ... -0.314500                    -   

            V23       V24       V25       V26       V27       V28   Amount  \
33755 -0.248812  0.335329  0.164725 -0.063462  0.010369  0.068737   300.00   
33756 -3.736852 -0.792271 -1.694790 -0.463947 -0.703180  0.780931  4476.72   
33757 -0.166334  1.008827  0.824605 -0.268009  0.016069  0.019513    28.56   
33758 -0.140236 -0.022273  0.117122 -0.358995 -0.201863  0.088919     0.00   
33759       NaN       NaN       NaN       NaN       NaN       NaN      NaN   

       Class  
33755    0.0  
33756    0.0  
33757    0.0  
33758    0.0  
33759    NaN  

[5 rows x 31 columns]

In [4]:
df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [5]:
df.dtypes

Time        int64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22        object
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
Class     float64
dtype: object

In [6]:
df.isna().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [7]:
df.dropna(inplace=True)

In [8]:
df.isna().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [9]:
df['Class'].value_counts()

Class
0.0    33656
1.0      103
Name: count, dtype: int64

In [10]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
x

array([[0, -1.3598071336738, -0.0727811733098497, ..., 0.133558376740387,
        -0.0210530534538215, 149.62],
       [0, 1.19185711131486, 0.26615071205963, ..., -0.0089830991432281,
        0.0147241691924927, 2.69],
       [1, -1.35835406159823, -1.34016307473609, ...,
        -0.0553527940384261, -0.0597518405929204, 378.66],
       ...,
       [37373, -7.50432315860846, -15.6337715288914, ...,
        -0.703180268852991, 0.780931395234091, 4476.72],
       [37373, 1.24254715717259, 0.0102971545545286, ...,
        0.016068593067795, 0.0195132871136261, 28.56],
       [37373, -1.0658646708338, 1.17747726970418, ...,
        -0.201863068578428, 0.0889189036678872, 0.0]], dtype=object)

In [11]:
y

array([0., 0., 0., ..., 0., 0., 0.])

In [12]:
from imblearn.over_sampling import SMOTE
smote=SMOTE(random_state=42)
x_resampled,y_resampled=smote.fit_resample(x,y)

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_resampled,y_resampled,test_size=0.30,random_state=42)
x_train

array([[ 7.11914340e+03, -3.32488381e+00,  2.03114061e+00, ...,
        -4.47791948e-01,  7.63994361e-01,  4.49338482e+01],
       [ 2.53799207e+04, -3.06291445e+00,  3.35414507e+00, ...,
         4.15070612e-01,  1.69431303e-01,  2.64995221e+01],
       [ 2.96341871e+04,  7.05709926e-01,  3.17259631e+00, ...,
         2.68465704e-01,  2.72029079e-01,  6.80000000e-01],
       ...,
       [ 2.95286282e+04, -3.44181450e-02,  2.71321677e+00, ...,
        -6.44779523e-02,  1.73744062e-01,  6.80000000e-01],
       [ 6.54000000e+02, -8.33568321e-01,  6.06174188e-01, ...,
         1.64383985e-01,  2.74361005e-01,  9.90000000e+00],
       [ 2.72350000e+04,  9.95760270e-01,  3.29195722e-01, ...,
        -6.59275185e-02,  1.53932099e-02,  1.13750000e+02]])

In [14]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit(x_train)
x_train=scalar.transform(x_train)
x_test=scalar.transform(x_test)

In [15]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([0., 1., 1., ..., 1., 0., 0.])

In [17]:
score=accuracy_score(y_test,y_pred)
score

0.9999009606813906

In [16]:
from sklearn.metrics import classification_report,accuracy_score
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     10078
         1.0       1.00      1.00      1.00     10116

    accuracy                           1.00     20194
   macro avg       1.00      1.00      1.00     20194
weighted avg       1.00      1.00      1.00     20194

